### PR TITLE
Update assets to Vue 2.5

### PR DESCRIPTION
**Pull request by YurySolovyov**
I didn't update `vuex` and `vue-router` to latest because there were semver-major changes with regards to typescript and I'm not sure how do we want to deal with them.

### CODE REVIEW

**Review by joshminnie — CHANGES_REQUESTED** [review]
This should probably update the README as well with the respective changes to the versions.

**Comment by YurySolovyov** [comment]
Hm, I think [it does](https://github.com/adambutler/vuejs-rails/pull/45/files#diff-1e290ac8433d555bce009b162cb869d0), or you mean something else?

**Comment by joshminnie** [comment]
Sorry, should have been more clear.

You made the comment about the semver major changes with regards to typescript. I was hoping to see more about that in the README for those who might not know why they were not the latest version.

**Comment by YurySolovyov** [comment]
Well, this particular PR does not yet contain semver-major stuff, so I guess we can mention it when we actually introduce these new assets

**Comment by phoet** [comment]
my assumption was that it would be safe to include the changes that break TS. wouldn't the TS compiler notice the incompatibilities?

**Comment by YurySolovyov** [comment]
Good point.
/cc @adambutler @kimyu92

**Comment by phoet** [comment]
i think that this can be closed now

**Pull request closed without merging**
