### PR TITLE
Updating Vue.js to lastest 1.0.4 version and add Vue resource (v0.1.16)

### PR DESCRIPTION
**Pull request by neolite**
Hi!
I'm updating Vue.js version to latest released version (1.04) and add vue-resource plugin.
Best regards!

### CODE REVIEW

**Comment by adambutler** [comment]
@neolite I see that this PR also adds Vue resource, would you please fix the conflict and I am happy to accept for this release.

**Comment by neolite** [comment]
Sync to base fork and fix

**Comment by adambutler** [comment]
@neolite Great... thank you!

**Comment by adambutler** [comment]
@Eric-Guo @neolite Just to confirm this is now deployed, thank you both for your contributions

**Comment by Eric-Guo** [comment]
:+1: thanks all.

**Comment by neolite** [comment]
Good!! Thanks all!

**Pull request merged**
