### PR TITLE
Upgrade vue 2.2.1 -> 2.3.2, vue-router, vuex and vue resource

### PR DESCRIPTION
**Pull request by kimyu92**
- Upgrade the following packages
  * vue - 2.3.0 [release](https://github.com/vuejs/vue/releases/tag/v2.3.0)
     - vue - 2.3.2 [release](https://github.com/vuejs/vue/releases/tag/v2.3.2)
  * vue-resource - 1.3.1 [release](https://github.com/pagekit/vue-resource/releases/tag/1.3.1)
  * vue-router - 2.5.2 [release](https://github.com/vuejs/vue-router/releases/tag/v2.5.2)
  * vuex - 2.3.0 [release](https://github.com/vuejs/vuex/releases/tag/v2.3.0)
- Update readme
- First release support minified and full versions of assets #39 🎉

### CODE REVIEW

**Comment by kimyu92** [comment]
cc @adambutler

**Comment by kimyu92** [comment]
@adambutler mind to make a release?

**Comment by YurySolovyov** [comment]
A friendly ping: Vue 2.3.3 is out (10d ago actually).
@adambutler is there a way we can have more people doing releases?

**Comment by adambutler** [comment]
😭 Sorry missed this... Can the collaborator sign up for RubyGems and provide me with your usernames I will then give you deploy access.

**Comment by YurySolovyov** [comment]
`YurySolovyov`

**Comment by adambutler** [comment]
I just noticed that I need an email... this makes things a little tricky since anyone could email me claiming to be you. I'd therefore like to ask if you could either:

a. Provide me your email publicly here. *or*

b. Provide me with your email signed against my Keybase.io profile (https://keybase.io/adamb) with your KeyBase being GitHub verified.

Happy to consider other options if you've got any other ideas how I can obtain your email securely in a verifiable way.

**Comment by YurySolovyov** [comment]
@adambutler `biohazard707@gmail.com`

**Comment by adambutler** [comment]
@YurySolovyov You are now a gem owner.

**Pull request merged**
